const React = require('react');
const ReactDOM = require('react-dom');

// Import component handle > file mappings generated by fractal (generate.js)
const components = require('./__components.js');

// Grab component data from DOM provided by server-side renderer (_preview.jsx)
/* eslint-disable no-underscore-dangle */
const data = window.__phenotypesReactData__;

// Re-render all React components on the page
data.forEach((item) => {
  const Component = components[item.baseHandle];
  const props = item.context;
  const root = document.getElementById(item.rootElementId);
  ReactDOM.render(<Component {...props} />, root);
});
